services:
  web:
    image: maio246/bgapp-web
    deploy:
      replicas: 5
    ports:
      - 8080:80
    volumes:
      - "/home/vagrant/containerization-course-app/web:/var/www/html:ro"
    networks:
      - app-network
  db:
    image: maio246/bgapp-db
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
secrets:
  db_root_password:
    external: true
networks:
  app-network:
